// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnomvjabxaiczxltwdub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub212amFieGFpY3p4bHR3ZHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzQ2OTIsImV4cCI6MjA3MDA1MDY5Mn0.UGYxMFn9jiS2rsWSNAp0eEaG2f6su3bjr6DhigdILN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});